# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170319_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='students',
            new_name='studentNums',
        ),
    ]
