# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170312_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_userd',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u4f7f\u7528'),
        ),
    ]
