# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-15 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverifyrecord_is_userd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverifyrecord',
            old_name='is_userd',
            new_name='is_used',
        ),
    ]
